import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await (await b.newContext({ viewport:{width:390,height:844}, hasTouch:true, isMobile:true })).newPage();
const errs = [];
p.on('pageerror', e => errs.push('PAGEERROR: '+e.message));
p.on('console', m => m.type()==='error' && !/net::ERR/.test(m.text()) && errs.push('CONSOLE: '+m.text()));
await p.goto('http://localhost:8099/', { waitUntil: 'networkidle' });
await p.waitForTimeout(600);
console.log('제목:', await p.title());
console.log('로고:', await p.locator('.home__logo').innerText());
await p.getByText('시작하기').click();
await p.waitForTimeout(500);
console.log('시작하기 후 URL:', p.url());
await p.screenshot({ path: '/tmp/claude-0/-home-user-hanjankak/dd91299a-0d6f-512e-b57e-691834267d02/scratchpad/root-base.png' });
console.log('에러:', errs.length ? errs : '없음');
await b.close();
